[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "deep-learning-tf-playground"
version = "0.1.0"
dependencies = ["tensorflow"]

[tool.setuptools.package-dir]
"" = "."

[tool.setuptools.packages.find]
where = ["."]